### ISSUE TITLE
Plastic box coloring non-efficient

### ISSUE THREAD

**Issue by Lanhild** [obl3pplifp/BlS-issue-tracker#240] opened 2020-10-28 18:37 UTC
When I put a dye to color plasticbox:plasticbox and then select "all" the dye doesn't have any effects. The block stays the color it was and the dye is consumed.

**Comment by fluxionary** [comment] 2020-10-28 18:42
Duplicate of #166

**Closed as completed by fluxionary** 2020-10-28 18:42 UTC
Labels: duplicate
