### ISSUE TITLE
Audit usage of minetest.get_connected_players()

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#181] opened 2020-03-03 13:54 UTC
Due to [a recent change in the Lua API](https://github.com/minetest/minetest/issues/9428), `minetest.get_connected_players()` now returns `nil` instead of `{}` if called before the game is initialized, which can cause mods that don't check for that behavior (probably most of them that are doing this) to crash the server before it starts. Before the next time we update the game engine, we will have to make sure that none of our mods do this. Apparently, as reported [here](https://forum.minetest.net/viewtopic.php?p=368257&sid=54e81d468ce2f0f813cc1f0091badc5b#p368257), we have at least one mod that does this. Here is a list of mods to review:

- [x] 3d_armor
- [x] ambience
- [x] areas
- [x] cloaking
- [x] cozy
- [x] currency
- [x] homedecor_modpack
- [x] hot_air_balloons
- [ ] irc2
- [ ] irc
- [x] jails
- [x] mesecons
- [x] missions
- [x] mobs_redo
- [x] more_mesecons
- [x] orienteering
- [x] other_worlds
- [x] playeranim
- [x] pmview
- [x] snippets
- [x] stamina
- [x] technic
- [x] titanium
- [x] unified_inventory
- [x] verbana
- [x] wielded_light

**Comment by sfan5** [comment] 2020-03-03 18:45
I have commented in the forum thread but will also say it here:
A server crash when a player <b>leaves</b> is not <i>wontfix/not a bug</i> like the linked issue. Please report it.

**Comment by luk3yx** [comment] 2020-03-03 20:06
I have created an issue (https://github.com/minetest/minetest/issues/9454).

**Closed as completed** 2020-03-04 09:36 UTC
Labels: bad crash, high priority

**Comment by fluxionary** [comment] 2020-03-04 10:25
luk, did you mean to close this? are the other mods OK?

**Comment by luk3yx** [comment] 2020-03-04 20:06
I tested a lot of mods while trying to replicate the crash, and I doubt the remaining mods would call `minetest.get_connected_players()` before the server starts.

**Comment by fluxionary** [comment] 2020-03-04 20:09
Alright, I might do some deeper auditing later if I feel up to it, but if you've at least tested them, that's probably enough.
