### ISSUE TITLE
Server exists.

### ISSUE THREAD

**Issue by corarona** [obl3pplifp/BlS-issue-tracker#275] opened 2021-01-20 12:07 UTC
The existence of this server has been nothing but a huge pain in the ** for the anarchy community. We demand you shut it down immediately (or at least remove easy access). As far as i can see nothing but harassment of people who have done NOTHING to you has come of this. And frankly i don't care if anyone has fun playing on the server. It's a nuisance TO ME. So shut it down already!!!!1 

That's you. 

Seriously.

_For anyone without a sense of humor: This is a joke. For some context; It's referring to this thread: https://github.com/EliasFleckenstein03/dragonfireclient/issues/22  _

**Comment by LizzyFleckenstein03** [comment] 2021-01-20 12:10
I totally agree.

**Comment by Code-Sploit** [comment] 2021-01-20 12:10
I agree aswell.

**Comment by TankTrooper** [comment] 2021-01-20 12:12
I could totally get behind this!

**Comment by LizzyFleckenstein03** [comment] 2021-01-20 12:12
A good temporary solution wood be to turn the server into a museum for now, meaning to revoke all privs from players.

**Comment by LizzyFleckenstein03** [comment] 2021-01-20 12:14
What???? You added the wontfix label??? Bruh

**Comment by Code-Sploit** [comment] 2021-01-20 12:15
Why would you add the wontfix label. This is not a bug!!! This will always be here!!!

**Comment by corarona** [comment] 2021-01-20 12:18
> What???? You added the wontfix label??? Bruh

I think this shows once and for all that it is indeed their intent to destroy our community :D

https://www.youtube.com/watch?v=a2krXq8fw90

**Comment by LizzyFleckenstein03** [comment] 2021-01-20 12:21
I feel like this escalated too fast.

**Comment by corarona** [comment] 2021-01-20 12:32
Nah it's all in good fun. Although you're probably right they'll likely get me banned on github  lol

**Comment by LizzyFleckenstein03** [comment] 2021-01-20 12:34
We might move to MeseHub. tacotexmex is not happy with the current performace (The app is really crashing all the time), so I offered him to host it on my server.

**Comment by TechDudie** [comment] 2021-01-20 16:00
#knockitoff

**Comment by luk3yx** [comment] 2021-01-20 18:01
I can't reproduce this problem. I've locked this issue to prevent any further arguing.

**Closed as completed by luk3yx** 2021-01-20 18:01 UTC
Labels: wontfix, ugh, can't confirm
