### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#164] opened 2019-12-12 03:31 UTC
```
2019-12-11 16:06:34: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'travelnet' in callback on_playerReceiveFields(): Invalid position (expected table got nil).
2019-12-11 16:06:34: ERROR[Main]: stack traceback:
2019-12-11 16:06:34: ERROR[Main]: 	[C]: in function 'get_meta'
2019-12-11 16:06:34: ERROR[Main]: 	/home/billys/.minetest/mods/travelnet/init.lua:214: in function </home/billys/.minetest/mods/travelnet/init.lua:205>
2019-12-11 16:06:34: ERROR[Main]: 	...minetest_exec/minetest5/bin/../builtin/game/register.lua:429: in function <...minetest_exec/minetest5/bin/../builtin/game/register.lua:413>
2019-12-11 16:06:34: ERROR[Main]: stack traceback:
2019-12-11 16:06:34: ERROR[Main]: 	[C]: in function 'get_meta'
2019-12-11 16:06:34: ERROR[Main]: 	/home/billys/.minetest/mods/travelnet/init.lua:214: in function </home/billys/.minetest/mods/travelnet/init.lua:205>
2019-12-11 16:06:34: ERROR[Main]: 	...minetest_exec/minetest5/bin/../builtin/game/register.lua:429: in function <...minetest_exec/minetest5/bin/../builtin/game/register.lua:413>
```

no idea what caused this. making a note here to look into it later.

**Comment by luk3yx** [comment] 2019-12-12 06:46
This is a possible crash that can be caused by malicious clients by specifying an invalid position in the formspec.

**Comment by luk3yx** [comment] 2019-12-12 06:49
Fixed in https://github.com/BlockySurvival/travelnet/commit/45acadea670c01413085017d6d9729548cb84fb4.

**Closed as completed** 2019-12-13 04:13 UTC
Labels: bug
