### ISSUE TITLE
PChests ownership and tubelib pushers

### ISSUE THREAD

**Issue by Lanhild** [obl3pplifp/BlS-issue-tracker#273] opened 2021-01-15 02:02 UTC
Portable chests content can be moved with a tubelib pusher, even if the chest isn't yours.

**Comment by oversword** [comment] 2021-01-15 06:41
*sigh* alright I'll add a checkbox so this issue doesn't keep coming up

**Comment by fluxionary** [comment] 2021-01-15 06:44
> _sigh_ alright I'll add a damn checkbox so you'll shut up about it

please be a bit more civil, this is a public repo. you guys should be setting an example for the other players.

**Comment by luk3yx** [comment] 2021-01-15 07:05
This is related to https://github.com/BlockySurvival/issue-tracker/issues/235, I'm not sure if it counts as a duplicate since this issue involves protected chests not locked chests.

**Comment by oversword** [comment] 2021-01-15 07:13
Actually @luk3yx this is a duplicate of https://github.com/BlockySurvival/issue-tracker/issues/267

**Comment by oversword** [comment] 2021-01-15 10:45
Ugh. Looks like this is actually custom code in bls_custom that makes pchests interact with tubelib, may still be possible, but messy.
I would very much like this to come after https://github.com/fluxionary/hook/pull/1 so I at least have some space to work with without hacking the formspec too much. Maybe tubelib functionality should be added in as a PR to the main / flux's fork of the project, and this new switch can come with it

**Comment by Lanhild** [comment] 2021-01-15 22:35
(No other chests affected, only pchests)

**Comment by oversword** [comment] 2021-01-26 02:54
This can be closed, flux just merged my changes

**Closed as completed** 2021-01-26 02:54 UTC
Labels: exploitable
